services:
  redis:
    image: "redis"

  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    user: celeryuser
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  backend:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - celery
    environment:
      - REDIS_URL=redis://redis:6379/0