# Generated by Django 5.2.4 on 2025-07-15 21:19

import api.models
import api.modelutils
import datetime
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIDataObject',
            fields=[
                ('id', models.UUIDField(default=api.modelutils.get_random_uuid, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(default=functools.partial(api.modelutils.get_future_date, *(datetime.timedelta(days=1),), **{}))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CeleryTaskMeta',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='UNKNOWN', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_ended', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('percent', models.FloatField(default=0)),
                ('successful', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleSequenceAlignment',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('fasta', models.FileField(null=True, upload_to=functools.partial(api.modelutils.get_user_spesific_path, *(), **{'subfolder': 'msa', 'suffix': '.fasta'}))),
                ('depth', models.IntegerField(default=0)),
                ('cols', models.IntegerField(default=0)),
                ('quality', models.IntegerField(choices=[(0, 'Na'), (1, 'Awful'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], default=0)),
            ],
            bases=('api.apidataobject',),
        ),
        migrations.CreateModel(
            name='PDB',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('name', models.CharField(max_length=200)),
                ('pdb_id', models.CharField(max_length=8)),
                ('pdb_file', models.FileField(null=True, upload_to=functools.partial(api.modelutils.get_user_spesific_path, *(), **{'subfolder': 'pdbs'}))),
                ('file_type', models.CharField(max_length=10)),
            ],
            bases=('api.apidataobject',),
        ),
        migrations.CreateModel(
            name='SeedSequence',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('name', models.CharField(max_length=200)),
                ('fasta', models.FileField(upload_to=functools.partial(api.modelutils.get_user_spesific_path, *(), **{'subfolder': 'seeds', 'suffix': '.fasta'}))),
            ],
            bases=('api.apidataobject',),
        ),
        migrations.CreateModel(
            name='StructureContacts',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('pdb_id', models.CharField(max_length=8)),
                ('ca_only', models.BooleanField()),
                ('threshold', models.IntegerField()),
                ('contacts', models.JSONField()),
            ],
            bases=('api.apidataobject',),
        ),
        migrations.CreateModel(
            name='EvolutionSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msa_file', models.FileField(upload_to=api.models.msa_upload_path)),
                ('nt_sequence', models.TextField()),
                ('steps', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('result_file', models.FileField(blank=True, null=True, upload_to=api.models.result_upload_path)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(default=functools.partial(api.modelutils.get_future_date, *(datetime.timedelta(days=1),), **{}))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectCouplingAnalysis',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('e_ij', api.modelutils.NdarrayField(null=True)),
                ('h_i', api.modelutils.NdarrayField(null=True)),
                ('ranked_di', api.modelutils.NdarrayField(null=True)),
                ('m_eff', models.IntegerField(null=True)),
                ('msa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.multiplesequencealignment')),
            ],
            bases=('api.apidataobject',),
        ),
        migrations.AddField(
            model_name='multiplesequencealignment',
            name='seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seedsequence'),
        ),
        migrations.CreateModel(
            name='MappedDi',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('protein_name', models.CharField(max_length=200)),
                ('mapped_di', api.modelutils.NdarrayField()),
                ('dca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.directcouplinganalysis')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seedsequence')),
            ],
            bases=('api.apidataobject',),
        ),
        migrations.CreateModel(
            name='APITaskMeta',
            fields=[
                ('celerytaskmeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.celerytaskmeta')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('expires', models.DateTimeField(default=functools.partial(api.modelutils.get_future_date, *(datetime.timedelta(days=1),), **{}))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.celerytaskmeta',),
        ),
    ]
