# Generated by Django 5.0.7 on 2024-08-05 03:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msa',
            name='fasta',
            field=models.FileField(null=True, unique=True, upload_to=api.models.get_msa_upload_to),
        ),
    ]
