# Generated by Django 5.0.7 on 2024-08-07 01:21

import api.modelutils
import datetime
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitaskmeta',
            name='expires',
            field=models.DateTimeField(default=functools.partial(api.modelutils.get_future_date, *(datetime.timedelta(days=1),), **{})),
        ),
    ]
