# Generated by Django 5.2.4 on 2025-07-17 20:11

import api.modelutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidataobject',
            name='user',
        ),
        migrations.AlterField(
            model_name='evolutionsimulation',
            name='id',
            field=models.UUIDField(default=api.modelutils.get_random_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
