# Generated by Django 5.0.7 on 2024-08-05 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_msa_fasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidataobject',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 4, 16, 40, 85811, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
