# Generated by Django 5.2.4 on 2025-07-17 20:23

import api.modelutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apidataobject_user_alter_evolutionsimulation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionsimulation',
            name='id',
            field=models.UUIDField(default=api.modelutils.get_random_uuid, primary_key=True, serialize=False),
        ),
    ]
