# Generated by Django 5.0.7 on 2024-08-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seedsequence_mappeddi'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureContacts',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('pdb_id', models.CharField(max_length=8)),
                ('ca_only', models.BooleanField()),
                ('threshold', models.IntegerField()),
                ('contacts', models.JSONField()),
            ],
            bases=('api.apidataobject',),
        ),
    ]
