# Generated by Django 5.1.1 on 2024-09-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_directcouplinganalysis_msa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMap',
        ),
    ]
