# Generated by Django 5.2.4 on 2025-07-21 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_evolutionsimulation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionsimulation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
