# Generated by Django 5.1.1 on 2024-10-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_contactmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidataobject',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apitaskmeta',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
