# Generated by Django 5.2.4 on 2025-07-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_evolutionsimulation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionsimulation',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionsimulation',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='simulation-results/'),
        ),
    ]
