# Generated by Django 5.2.4 on 2025-07-23 16:33

import api.modelutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_evolutionsimulation_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionsimulation',
            name='id',
            field=models.UUIDField(default=api.modelutils.get_random_uuid, primary_key=True, serialize=False),
        ),
    ]
