# Generated by Django 5.2.3 on 2025-06-26 22:37

import api.modelutils
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apidataobject_session_key_apitaskmeta_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDB',
            fields=[
                ('apidataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.apidataobject')),
                ('name', models.CharField(max_length=200)),
                ('pdb_id', models.CharField(max_length=8)),
                ('pdb_file', models.FileField(null=True, upload_to=functools.partial(api.modelutils.get_user_spesific_path, *(), **{'subfolder': 'pdbs'}))),
                ('file_type', models.CharField(max_length=10)),
            ],
            bases=('api.apidataobject',),
        ),
    ]
