# Generated by Django 5.2.4 on 2025-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_evolutionsimulation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionsimulation',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
